pipeline {
    agent any

    environment {
        IMAGE_NAME = "ananya559/myapp"
    }

    stages {

        stage('Login to Docker Hub') {
            steps {
                withCredentials([string(credentialsId: 'dockerhub-token', variable: 'DOCKER_TOKEN')]) {
                    bat '''
                    echo Logging into Docker...
                    echo %DOCKER_TOKEN%>token.txt
                    docker login -u ananya559 --password-stdin < token.txt
                    del token.txt
                    '''
                }
            }
        }
        
        stage('Build Docker Image') {
            steps {
                dir('lab/exp7') {
                    bat 'docker build -t %IMAGE_NAME%:latest .'
                }
            }
        }


        stage('Push to Docker Hub') {
            steps {
                bat 'docker push %IMAGE_NAME%:latest'
            }
        }
    }
}
