pipeline {
    agent any

    environment {
        IMAGE_NAME = "ananya559/myapp"
    }

    stages {

        stage('Build Docker Image') {
            steps {
                dir('lab/exp7/my-app') {
                    bat 'docker build -t %IMAGE_NAME%:latest .'
                }
            }
        }

        stage('Login to Docker Hub') {
            steps {
                withCredentials([string(credentialsId: 'dockerhub-token', variable: 'DOCKER_TOKEN')]) {
                    bat 'echo %DOCKER_TOKEN% | docker login -u ananya559 --password-stdin'
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                bat 'docker push %IMAGE_NAME%:latest'
            }
        }
    }
}